FROM lylandris/p4env:base
MAINTAINER lylandris

RUN set -xe \
    && mkdir -p /root/.ssh && chmod 700 /root/.ssh

ADD authorized_keys /root/.ssh/authorized_keys

EXPOSE 22

ENTRYPOINT /usr/sbin/sshd -D
